Make PFAIR optional to prevent build and runtime failures.
The PFAIR plugin always implicitly assumed !NO_HZ (the schedule
is wrong if NO_HZ is enabled) and does not built if hrtimers are absent:

> litmus/built-in.o: In function `pfair_activate_plugin':
> sched_pfair.c:(.text+0x7f07): undefined reference to `cpu_stagger_offset'
> litmus/built-in.o: In function `init_pfair':
> sched_pfair.c:(.init.text+0x487): undefined reference to `cpu_stagger_offset'

cpu_stagger_offset() is only available if hrtimers are enabled.

This patch makes these dependencies explicit.